//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProject_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedEmployees
    {
        public int EmployeeNumber { get; set; }
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> StartWorking { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<int> NumberReason { get; set; }
        public string Reason { get; set; }
        public string ManagerAccess { get; set; }
        public string Details { get; set; }
    
        public virtual ReasonsForLeaving ReasonsForLeaving { get; set; }
    }
}
