//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProject_Final
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProjDbContext : DbContext
    {
        public FinalProjDbContext()
            : base("name=FinalProjDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeletedEmployees> DeletedEmployees { get; set; }
        public virtual DbSet<DeletedVehicles> DeletedVehicles { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<PickUps> PickUps { get; set; }
        public virtual DbSet<ReasonsDeleteVehicles> ReasonsDeleteVehicles { get; set; }
        public virtual DbSet<ReasonsForLeaving> ReasonsForLeaving { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<VehiclesTypes> VehiclesTypes { get; set; }
        public virtual DbSet<OrderUpdates> OrderUpdates { get; set; }
    }
}
