//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProject_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.PickUps = new HashSet<PickUps>();
            this.OrderUpdates = new HashSet<OrderUpdates>();
        }
    
        public int OrderNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Pssengers { get; set; }
        public string Details { get; set; }
        public Nullable<int> Driver { get; set; }
        public string Vehicle { get; set; }
        public string OrderStatus { get; set; }
        public string Type { get; set; }
        public Nullable<int> Bid { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickUps> PickUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderUpdates> OrderUpdates { get; set; }
    }
}
