//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProject_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public string VehicleNumber { get; set; }
        public string Manufacturer { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TestValidityDate { get; set; }
        public Nullable<System.DateTime> EntryCompany { get; set; }
        public string Remarks { get; set; }
        public string Img { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual VehiclesTypes VehiclesTypes { get; set; }
    }
}
